trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  containerRegistryServiceConnection: uniappsoigiga
  kubernetesServiceConnection: $(KUBERNETES_SERVICE_CONNECTION)
  kubernetesNamespace: $(KUBERNETES_NAMESPACE)
  dagsterImageRepository: $(DAGSTER_IMAGE_REPOSITORY)
  system.debug: true

steps:
  - task: Bash@3
    displayName: Get short commit hash
    inputs:
      targetType: inline
      script: "SHORT_SHA=`git rev-parse --short HEAD`"
      workingDirectory: $(Build.SourcesDirectory)

  - task: Docker@2
    displayName: Login to container Registry
    inputs:
      command: login
      containerRegistry: $(containerRegistryServiceConnection)

  - task: Docker@2
    displayName: Build and push image to container registry
    inputs:
      command: buildAndPush
      repository: giga-dagster
      dockerfile: $(Build.SourcesDirectory)/Dockerfile.prod
      containerRegistry: $(containerRegistryServiceConnection)
      tags: |
        $(Build.SourceVersion)

  - task: HelmDeploy@0
    displayName: Add Dagster Helm Repo
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)
      command: repo
      arguments: dagster https://dagster-io.github.io/helm
      namespace: $(kubernetesNamespace)

  - task: HelmDeploy@0
    displayName: Helm deploy Dagster core
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)
      command: upgrade
      chartType: Name
      chartName: dagster/dagster
      releaseName: dagster
      namespace: $(kubernetesNamespace)
      arguments: |
        --values infra/helm/values.yaml \
        --set dagster-user-deployments.deployments[0].image.repository="$(containerRegistryServiceConnection).azurecr.io" \
        --set dagster-user-deployments.deployments[0].image.tag=$SHORT_SHA \
        --set pipelineRun.image.repository="$(containerRegistryServiceConnection).azurecr.io" \
        --set pipelineRun.image.tag=$SHORT_SHA

  - task: HelmDeploy@0
    displayName: Helm deploy Dagster user code
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)
      command: upgrade
      chartType: Name
      chartName: dagster/dagster-user-deployments
      releaseName: dagster-user-code
      namespace: $(kubernetesNamespace)
      arguments: |
        --values infra/helm/user-code-values.yaml \
        --set deployments[0].image.repository="$(containerRegistryServiceConnection).azurecr.io" \
        --set deployments[0].image.tag=$SHORT_SHA
