trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - docs

pr:
  autoCancel: true
  drafts: true
  paths:
    exclude:
      - docs

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - template: templates/test-workflow.yaml
    condition: eq(Build.Reason, 'PullRequest')

  - template: templates/deploy-workflow.yaml
    condition: not(eq(Build.Reason, 'PullRequest'))
