trigger:
  branches:
    include:
      - staging

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  containerRegistryName: $(ACR_NAME)
  containerRegistryServiceConnection: $(ACR_SERVICE_CONNECTION)
  kubernetesEnvironment: $(KUBERNETES_ENVIRONMENT)
  kubernetesNamespace: $(KUBERNETES_NAMESPACE)
  postgresqlUsername: $(POSTGRESQL_USERNAME)
  postgresqlPassword: $(POSTGRESQL_PASSWORD)
  azureSasToken: $(AZURE_SAS_TOKEN)
  azureBlobSasHost: $(AZURE_BLOB_SAS_HOST)
  azureDfsSasHost: $(AZURE_DFS_SAS_HOST)
  azureBlobContainerName: $(AZURE_BLOB_CONTAINER_NAME)
  azureStorageAccountName: $(AZURE_STORAGE_ACCOUNT_NAME)
  azureAdTenantId: $(AZURE_TENANT_ID)
  azureAdClientId: $(AZURE_CLIENT_ID)
  azureAdClientSecret: $(AZURE_CLIENT_SECRET)
  azureAdTenantName: $(AZURE_TENANT_NAME)
  azureAdPolicyName: $(AZURE_AUTH_POLICY_NAME)
  azureAdRedirectUri: $(AZURE_REDIRECT_URI)
  azureAdLogoutRedirectUri: $(AZURE_LOGOUT_REDIRECT_URI)
  secretKey: $(AUTHPROXY_SECRET_KEY)
  datahubAccessToken: $(DATAHUB_ACCESS_TOKEN)
  sparkRpcAuthSecret: $(SPARK_RPC_AUTHENTICATION_SECRET)
  datahubAzureAdClientSecret: $(DATAHUB_AZURE_CLIENT_SECRET)
  datahubAzureAdRedirectUrl: $(DATAHUB_AZURE_REDIRECT_URL)
  system.debug: true

stages:
  - stage: Delete
    displayName: Delete Dagster
    jobs:
      - deployment: Delete
        displayName: Delete Dagster deployment
        environment: $(kubernetesEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmDeploy@0
                  displayName: Helm uninstall authproxy
                  inputs:
                    namespace: $(kubernetesNamespace)
                    command: uninstall
                    arguments: dagster-authproxy

                - task: HelmDeploy@0
                  displayName: Helm uninstall Dagster
                  inputs:
                    namespace: $(kubernetesNamespace)
                    command: uninstall
                    arguments: dagster

                - task: HelmDeploy@0
                  displayName: Helm uninstall Spark
                  inputs:
                    namespace: $(kubernetesNamespace)
                    command: uninstall
                    arguments: spark

                - task: Kubernetes@1
                  displayName: Delete resources in namespace
                  inputs:
                    command: delete
                    arguments: all --all
                    namespace: $(kubernetesNamespace)

                - task: Kubernetes@1
                  displayName: Delete PVCs in namespace
                  continueOnError: true
                  inputs:
                    command: delete
                    arguments: pvc --all
                    namespace: $(kubernetesNamespace)
