x-common-config: &common-config
  init: true
  restart: unless-stopped

services:
  dagster-storage:
    <<: *common-config
    image: bitnami/postgresql:14
    env_file: ./dagster/.env
    volumes:
      - dagster-data:/bitnami/postgresql

  dagster:
    <<: *common-config
    build: ./dagster
    image: unicef/giga-dataops-platform/dagster
    env_file: ./dagster/.env
    environment:
      DAGSTER_HOME: /app
    volumes:
      - ./dagster:/app
    depends_on:
      - dagster-storage

  authproxy:
    <<: *common-config
    build: ./authproxy
    image: unicef/giga-dataops-platform/dagster-authproxy
    env_file: ./authproxy/.env
    volumes:
      - ./authproxy:/app
    ports:
      - "3001:3001"

volumes:
  dagster-data:
