parameters:
  - name: displayName
  - name: repository
  - name: dockerfile

jobs:
  - deployment: Deploy
    displayName: Build and push ${{ parameters.displayName }}
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Docker@2
              displayName: Login to container Registry
              inputs:
                command: login
                containerRegistry: $(ACR_SERVICE_CONNECTION)

            - task: Docker@2
              displayName: Build and push ${{ parameters.displayName }} image to container registry
              inputs:
                command: buildAndPush
                repository: ${{ parameters.repository }}
                dockerfile: ${{ parameters.dockerfile }}
                containerRegistry: $(ACR_SERVICE_CONNECTION)
                tags: |
                  $(Build.SourceVersion)
